name: Sync Reading List

on:
  schedule:
    # Run daily at 8 AM UTC
    - cron: '0 8 * * *'
  workflow_dispatch:
    # Allow manual trigger
  push:
    branches: [ main ]
    paths:
      - 'scripts/**'
      - 'config.json'

permissions:
  contents: write

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        cd frontend && npm ci

    - name: Create data directory
      run: mkdir -p data

    - name: Fetch dev.to reading list
      run: |
        if [ -n "${{ secrets.DEVTO_API_KEY }}" ]; then
          npm run fetch:devto
        else
          echo "DEVTO_API_KEY not set, skipping fetch:devto"
        fi
      env:
        DEVTO_API_KEY: ${{ secrets.DEVTO_API_KEY }}

    - name: Fetch daily.dev bookmarks
      run: |
        if [ -n "${{ secrets.DAILYDEV_RSS_URL }}" ]; then
          npm run fetch:dailydev
        else
          echo "DAILYDEV_RSS_URL not set, skipping fetch:dailydev"
        fi
      env:
        DAILYDEV_RSS_URL: ${{ secrets.DAILYDEV_RSS_URL }}

    - name: Verify data files were updated
      run: |
        echo "=== Verifying data files ==="
        echo "dailydev.json last_updated:"
        cat data/dailydev.json | grep "last_updated" || echo "No last_updated found"
        echo "devto.json last_updated:"
        cat data/devto.json | grep "last_updated" || echo "No last_updated found"
        echo "File timestamps:"
        ls -la data/
        echo "Current time: $(date -u)"

    - name: Set Git identity
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

    - name: Build frontend
      run: npm run build

    - name: Copy data to frontend/dist
      run: |
        echo "Current directory: $(pwd)"
        echo "Data directory contents:"
        ls -la data/
        echo "Data file timestamps:"
        stat data/dailydev.json || echo "dailydev.json not found"
        stat data/devto.json || echo "devto.json not found"
        echo "Frontend dist directory contents:"
        ls -la frontend/dist/ || echo "frontend/dist/ does not exist yet"
        echo "Force copying data to frontend/dist..."
        cp -rfv data/ frontend/dist/
        echo "After copy - frontend/dist/ contents:"
        ls -la frontend/dist/
        echo "Data files in frontend/dist/data/:"
        ls -la frontend/dist/data/ || echo "No data files found"
        echo "Verifying copied file timestamps:"
        stat frontend/dist/data/dailydev.json || echo "dailydev.json not found in dist"
        stat frontend/dist/data/devto.json || echo "devto.json not found in dist"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend/dist
        force_orphan: true